version: "3.8"

services:

  # Here goes my dockerized apps i.e.
  air_bot_app:
    image: ghcr.io/rafalkk/air_bot:latest # to use watchtower with private images on docker hub you need use the full image name, including the repository prefix index.docker.io
    environment:
      - TELEGRAM_BOT_API_KEY=
      - PROXY_API_KEY=
    container_name: air-bot

  # Watchtower keeps docker containers up to date
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - WATCHTOWER_POLL_INTERVAL=10 # seconds
    command: air-bot # only scan for container with that name
    container_name: watchtower




